# Generated by Django 4.1.13 on 2024-05-20 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unix_aquatics', models.TextField(default=None)),
                ('vision', models.TextField(default=None)),
                ('mission', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HomePageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(upload_to='home_page')),
                ('welcome_message', models.TextField()),
                ('cta_button_text', models.CharField(max_length=50)),
                ('cta_button_link', models.URLField()),
                ('recent_updates_or_news', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NewProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('date_of_establishment', models.DateField()),
                ('number_of_ponds', models.PositiveIntegerField()),
                ('water_capacity', models.FloatField()),
                ('annual_production_capacity', models.FloatField()),
                ('capital', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_shares', models.PositiveIntegerField()),
                ('price_per_share', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='OtherProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Projectpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proname', models.CharField(default='name', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('projectlogo', models.ImageField(blank=True, default='images/profilepicdefalt.png', max_length=200, null=True, upload_to='project_logos/')),
                
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='team_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='CustomProjectpageAdmin',
            fields=[
                ('projectpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fasu.projectpage')),
            ],
            bases=('fasu.projectpage',),
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fasu.projectpage')),
            ],
        ),
        migrations.CreateModel(
            name='MyProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectlogo', models.ImageField(blank=True, null=True, upload_to='projectlogo_attachments/')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('date_of_establishment', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('number_of_ponds', models.PositiveIntegerField(blank=True, null=True)),
                ('water_capacity', models.FloatField(blank=True, null=True)),
                ('annual_production_capacity', models.FloatField(blank=True, null=True)),
                ('capital', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('number_of_shares', models.PositiveIntegerField(blank=True, null=True)),
                ('price_per_share', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('investment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('investment_date', models.DateField(blank=True, null=True)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='investment_receipts/')),
                ('installments', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('total_investment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_number_of_shares', models.PositiveIntegerField(blank=True, null=True)),
                ('investment_price_per_share', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shares_holding', models.PositiveIntegerField(default=0)),
                ('share_certificate', models.FileField(blank=True, null=True, upload_to='share_certificates/')),
                ('dividend_date', models.DateField(blank=True, null=True)),
                ('dividend_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('transfer_proof', models.FileField(blank=True, null=True, upload_to='dividend_transfer_proof/')),
                ('total_dividend', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('partnership_agreement', models.FileField(blank=True, null=True, upload_to='partnership_agreements/')),
                ('other_agreements', models.FileField(blank=True, null=True, upload_to='other_agreements/')),
                ('project_images', models.ImageField(blank=True, null=True, upload_to='project_images/')),
                ('project_videos', models.FileField(blank=True, null=True, upload_to='project_videos/')),
                ('project_live', models.BooleanField(default=False)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fasu.newproject')),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvestorProfile',
            fields=[
                ('profilepic', models.ImageField(blank=True, upload_to='profilpic_attachments/')),
                ('profilepicname', models.CharField(blank=True, max_length=15, null=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('whatsapp', models.CharField(blank=True, max_length=15, null=True)),
                ('aadhar_card', models.CharField(blank=True, max_length=12, null=True)),
                ('aadhar_card_attachment', models.FileField(blank=True, null=True, upload_to='aadhar_card_attachments/')),
                ('election_id', models.CharField(blank=True, max_length=20, null=True)),
                ('election_id_attachment', models.FileField(blank=True, null=True, upload_to='election_id_attachments/')),
                ('passport_number', models.CharField(blank=True, max_length=20, null=True)),
                ('passport_attachment', models.FileField(blank=True, null=True, upload_to='passport_attachments/')),
                ('pan_card_number', models.CharField(blank=True, max_length=10, null=True)),
                ('pan_card_attachment', models.FileField(blank=True, null=True, upload_to='pan_card_attachments/')),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('iban', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_account_passbook_attachment', models.FileField(blank=True, null=True, upload_to='bank_account_passbook_attachments/')),
                ('id', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fasu.projectpage')),
            ],
        ),
    ]
