# Generated by Django 5.0.6 on 2024-12-09 20:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unix_aquatics', models.TextField(default=None)),
                ('vision', models.TextField(default=None)),
                ('mission', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Projectpage',
            fields=[
                ('description', models.TextField(blank=True, null=True)),
                ('projectlogo', models.ImageField(blank=True, default='images/profilepicdefalt.png', max_length=200, null=True, upload_to='project_logos/')),
                ('projectlogoname', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('date_of_establishment', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('number_of_ponds', models.PositiveIntegerField(blank=True, null=True)),
                ('water_capacity', models.FloatField(blank=True, null=True)),
                ('annual_production_capacity', models.FloatField(blank=True, null=True)),
                ('capital', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('number_of_shares', models.PositiveIntegerField(blank=True, null=True)),
                ('price_per_share', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('proname', models.CharField(default='name', max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomePageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(upload_to='home_page')),
                ('welcome_message', models.TextField()),
                ('cta_button_text', models.CharField(max_length=50)),
                ('cta_button_link', models.URLField()),
                ('recent_updates_or_news', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, default='New image uploaded', max_length=255, null=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('imagename', models.CharField(blank=True, max_length=100, null=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=100)),
                ('projectname', models.CharField(default=None, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('last_uploaded_image_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='team_photos/')),
                ('photoname', models.TextField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, upload_to='videos/')),
                ('videoname', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_upload', models.DateField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Whatsappchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomProjectpageAdmin',
            fields=[
                ('projectpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fasu.projectpage')),
            ],
            options={
                'abstract': False,
            },
            bases=('fasu.projectpage',),
        ),
        migrations.CreateModel(
            name='InvestorProfile',
            fields=[
                ('profilepic', models.ImageField(blank=True, upload_to='profilpic_attachments/')),
                ('profilepicname', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('whatsapp', models.CharField(blank=True, max_length=15, null=True)),
                ('aadhar_card', models.CharField(blank=True, max_length=12, null=True)),
                ('aadhar_card_attachment', models.FileField(blank=True, null=True, upload_to='aadhar_card_attachments/')),
                ('election_id', models.CharField(blank=True, max_length=20, null=True)),
                ('election_id_attachment', models.FileField(blank=True, null=True, upload_to='election_id_attachments/')),
                ('passport_number', models.CharField(blank=True, max_length=20, null=True)),
                ('passport_attachment', models.FileField(blank=True, null=True, upload_to='passport_attachments/')),
                ('pan_card_number', models.CharField(blank=True, max_length=10, null=True)),
                ('pan_card_attachment', models.FileField(blank=True, null=True, upload_to='pan_card_attachments/')),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('iban', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_account_passbook_attachment', models.FileField(blank=True, null=True, upload_to='bank_account_passbook_attachments/')),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyProjects',
            fields=[
                ('description', models.TextField(blank=True, null=True)),
                ('projectlogo', models.ImageField(blank=True, default='images/profilepicdefalt.png', max_length=200, null=True, upload_to='project_logos/')),
                ('projectlogoname', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('date_of_establishment', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('number_of_ponds', models.PositiveIntegerField(blank=True, null=True)),
                ('water_capacity', models.FloatField(blank=True, null=True)),
                ('annual_production_capacity', models.FloatField(blank=True, null=True)),
                ('capital', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('number_of_shares', models.PositiveIntegerField(blank=True, null=True)),
                ('price_per_share', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project', models.CharField(blank=True, max_length=50, null=True)),
                ('end_date', models.DateField(blank=True, default=None, null=True)),
                ('investment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('investment_date', models.DateField(blank=True, null=True)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='investment_receipts/')),
                ('installments', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('total_investment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_number_of_shares', models.PositiveIntegerField(blank=True, null=True)),
                ('investment_price_per_share', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('shares_holding', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('share_certificate', models.FileField(blank=True, null=True, upload_to='share_certificates/')),
                ('dividend_date', models.DateField(blank=True, null=True)),
                ('dividend_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('transfer_proof', models.FileField(blank=True, null=True, upload_to='dividend_transfer_proof/')),
                ('total_dividend', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('partnership_agreement', models.FileField(blank=True, null=True, upload_to='partnership_agreements/')),
                ('other_agreements', models.FileField(blank=True, null=True, upload_to='other_agreements/')),
                ('proname', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='fasu.projectpage')),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='fasu.video')),
            ],
        ),
    ]
