# Generated by Django 5.0.6 on 2024-12-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fasu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videonotification',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='videonotification',
            name='video',
        ),
        migrations.AddField(
            model_name='videonotification',
            name='last_uploaded_video_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='videonotification',
            name='message',
            field=models.CharField(max_length=255),
        ),
    ]
