# Generated by Django 4.1.13 on 2024-05-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fasu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='prologoname',
            field=models.TextField(blank=True, null=True),
        ),
    ]
