# Generated by Django 4.1.13 on 2024-05-20 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fasu', '0002_projectpage_prologoname'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='photoname',
            field=models.TextField(blank=True, null=True),
        ),
    ]
