# Generated by Django 5.0.6 on 2024-12-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fasu', '0002_backgroundimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundimage',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
