# Generated by Django 5.0.6 on 2024-12-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fasu', '0003_video_message_alter_myprojects_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='backgroundimage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bg_image', models.ImageField(upload_to='bg_image')),
            ],
        ),
    ]
