# Generated by Django 5.0.6 on 2024-12-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fasu', '0003_backgroundimage_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backgroundimage',
            name='bg_image',
        ),
        migrations.AddField(
            model_name='backgroundimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='background_images/'),
        ),
        migrations.AlterField(
            model_name='backgroundimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
