# Generated by Django 4.1.13 on 2024-05-20 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fasu', '0003_teammember_photoname'),
    ]

    operations = [
        migrations.AddField(
            model_name='myproject',
            name='projectlogoname',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
