# Generated by Django 4.1.13 on 2024-05-20 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fasu', '0004_myproject_projectlogoname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproject',
            name='projectlogoname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
