# Generated by Django 5.0.6 on 2024-12-13 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fasu', '0005_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
