# Generated by Django 5.1.4 on 2024-12-18 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fasu', '0006_location_location_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dividend_date', models.DateField(blank=True, null=True)),
                ('dividend_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('transfer_proof', models.FileField(blank=True, null=True, upload_to='dividend_transfer_proof/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividends', to='fasu.myprojects')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividends', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]

