# Generated by Django 4.1.13 on 2024-05-21 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fasu', '0006_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
