# Generated by Django 4.1.13 on 2024-05-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fasu', '0007_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, upload_to='videos')),
                ('viseoname', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_upload', models.DateField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
