# Generated by Django 4.1.13 on 2024-05-21 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fasu', '0008_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='viseoname',
            new_name='videoname',
        ),
    ]
