# Generated by Django 4.1.13 on 2024-05-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fasu', '0009_rename_viseoname_video_videoname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
    ]
